### ISSUE TITLE
add data base configuration to configuration file and throw an exception if on of the services (db/payment/supply) doesn't exist

### ISSUE THREAD

**Issue by dollshak** [AyalaBadash/market_2022#317]

**Comment by BARDAMRI** [comment]
The file and reading method are done.
Need only to use the data in the db init.

**Comment by dollshak** [comment]
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11500174
spring.datasource.username=sql11500174
spring.datasource.password=ZiXKWjKUpq

**Comment by livneido1** [comment]
with the values @dollshak  will provide here:

- [ ] read files from configuration file
- [ ] write files to application.properties (you can see an example of reading from .properties files in ConfigReader)
- [ ] create tests - success test for all parameters, fail tests for each parameter.

**Comment by BARDAMRI** [comment]
Done. you can see the init in DataSourceConfigReader class and the values in application.properties as needed.
please check the values are right.
