### ISSUE TITLE
checkSystemInit - figure where to put it

### ISSUE THREAD

**Issue by livneido1** [AyalaBadash/market_2022#329]
- [x] now - it logs for bad services and whatever - why? if we are not using pre given data it should do it with default services
- [x] should inform for bad manger if not using data. 
- [x] if problems occurred - need to be if error or warn logger and not info

**Comment by BARDAMRI** [comment]
-There are no default services. If there were the system will never have a problem with init from file.
-should inform for bad manger if not using data. what does it mean
