### ISSUE TITLE
disable reading config and data if not needed

### ISSUE THREAD

**Issue by livneido1** [AyalaBadash/market_2022#340]
- [x] data should be read only once if config is true, not each time server is asked if is init already;
- [x] config reader. i think it should be read once aswell. let me know if not. if so. fix it
- [x] for some reason data is always loaded. even if MarketConfig.LoadData = fasle it creates u1 an do soo on can see picture
![image](https://user-images.githubusercontent.com/62897121/174897672-d8a66932-b4bb-458c-9865-37af2482ecbf.png)

**Comment by BARDAMRI** [comment]
* there is MarketConfig.USING_DATA that checked in the init. you only need to set it to false.
* fixed.
* The u1 is in the services file. I changed the init method so it will not init it automatically now.
